"""Inital Migration: Create Tables

Revision ID: c3b924712e7d
Revises: 
Create Date: 2025-11-11 23:00:17.051145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b924712e7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('cuisine', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('serving_size', sa.String(length=100), nullable=True),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=False),
    sa.Column('rest_time_minutes', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('carbs_g', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('fat_g', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('fiber_g', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('sodium_mg', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('cook_time_minutes >= 0', name='check_cook_time_non_negative'),
    sa.CheckConstraint('prep_time_minutes >= 0', name='check_prep_time_non_negative'),
    sa.CheckConstraint('rest_time_minutes >= 0', name='check_rest_time_non_negative'),
    sa.CheckConstraint('servings > 0', name='check_servings_positive'),
    sa.CheckConstraint('version > 0', name='check_version_positive'),
    sa.CheckConstraint('view_count >= 0', name='check_view_count_non_negative'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipes_author_created', 'recipes', ['author_id', 'created_at'], unique=False)
    op.create_index('idx_recipes_deleted_at_created', 'recipes', ['deleted_at', 'created_at'], unique=False)
    op.create_index('idx_recipes_difficulty_cuisine', 'recipes', ['difficulty', 'cuisine'], unique=False)
    op.create_index(op.f('ix_recipes_author_id'), 'recipes', ['author_id'], unique=False)
    op.create_index(op.f('ix_recipes_created_at'), 'recipes', ['created_at'], unique=False)
    op.create_index(op.f('ix_recipes_cuisine'), 'recipes', ['cuisine'], unique=False)
    op.create_index(op.f('ix_recipes_deleted_at'), 'recipes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_recipes_difficulty'), 'recipes', ['difficulty'], unique=False)
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_index(op.f('ix_recipes_view_count'), 'recipes', ['view_count'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity_value', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('quantity_unit', sa.String(length=50), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=False),
    sa.Column('is_dairy_free', sa.Boolean(), nullable=False),
    sa.Column('allergens', sa.JSON(), nullable=False),
    sa.Column('substitutes', sa.JSON(), nullable=False),
    sa.CheckConstraint('quantity_value > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ingredients_dietary', 'ingredients', ['is_vegan', 'is_vegetarian', 'is_gluten_free'], unique=False)
    op.create_index('idx_ingredients_recipe_name', 'ingredients', ['recipe_id', 'name'], unique=False)
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_index(op.f('ix_ingredients_recipe_id'), 'ingredients', ['recipe_id'], unique=False)
    op.create_table('recipe_favorites',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorited_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'user_id')
    )
    op.create_index('idx_recipe_favorites_recipe_id', 'recipe_favorites', ['recipe_id'], unique=False)
    op.create_index('idx_recipe_favorites_user_id', 'recipe_favorites', ['user_id'], unique=False)
    op.create_table('recipe_meal_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'meal_type', name='uq_recipe_meal_type')
    )
    op.create_index('idx_meal_types_type_recipe', 'recipe_meal_types', ['meal_type', 'recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_meal_types_id'), 'recipe_meal_types', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_meal_types_recipe_id'), 'recipe_meal_types', ['recipe_id'], unique=False)
    op.create_table('recipe_reviews',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'user_id')
    )
    op.create_index('idx_recipe_reviews_recipe_id', 'recipe_reviews', ['recipe_id'], unique=False)
    op.create_index('idx_recipe_reviews_user_id', 'recipe_reviews', ['user_id'], unique=False)
    op.create_table('recipe_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('technique', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.String(length=50), nullable=True),
    sa.Column('ingredients_used', sa.JSON(), nullable=False),
    sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes >= 0', name='check_duration_non_negative'),
    sa.CheckConstraint('step_number > 0', name='check_step_number_positive'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'step_number', name='uq_recipe_step_number')
    )
    op.create_index('idx_steps_recipe_number', 'recipe_steps', ['recipe_id', 'step_number'], unique=False)
    op.create_index(op.f('ix_recipe_steps_id'), 'recipe_steps', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_steps_recipe_id'), 'recipe_steps', ['recipe_id'], unique=False)
    op.create_table('recipe_tags',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'tag_id')
    )
    op.create_index('idx_recipe_tags_recipe_id', 'recipe_tags', ['recipe_id'], unique=False)
    op.create_index('idx_recipe_tags_tag_id', 'recipe_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recipe_tags_tag_id', table_name='recipe_tags')
    op.drop_index('idx_recipe_tags_recipe_id', table_name='recipe_tags')
    op.drop_table('recipe_tags')
    op.drop_index(op.f('ix_recipe_steps_recipe_id'), table_name='recipe_steps')
    op.drop_index(op.f('ix_recipe_steps_id'), table_name='recipe_steps')
    op.drop_index('idx_steps_recipe_number', table_name='recipe_steps')
    op.drop_table('recipe_steps')
    op.drop_index('idx_recipe_reviews_user_id', table_name='recipe_reviews')
    op.drop_index('idx_recipe_reviews_recipe_id', table_name='recipe_reviews')
    op.drop_table('recipe_reviews')
    op.drop_index(op.f('ix_recipe_meal_types_recipe_id'), table_name='recipe_meal_types')
    op.drop_index(op.f('ix_recipe_meal_types_id'), table_name='recipe_meal_types')
    op.drop_index('idx_meal_types_type_recipe', table_name='recipe_meal_types')
    op.drop_table('recipe_meal_types')
    op.drop_index('idx_recipe_favorites_user_id', table_name='recipe_favorites')
    op.drop_index('idx_recipe_favorites_recipe_id', table_name='recipe_favorites')
    op.drop_table('recipe_favorites')
    op.drop_index(op.f('ix_ingredients_recipe_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_index('idx_ingredients_recipe_name', table_name='ingredients')
    op.drop_index('idx_ingredients_dietary', table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_recipes_view_count'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_difficulty'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_deleted_at'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_cuisine'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_created_at'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_author_id'), table_name='recipes')
    op.drop_index('idx_recipes_difficulty_cuisine', table_name='recipes')
    op.drop_index('idx_recipes_deleted_at_created', table_name='recipes')
    op.drop_index('idx_recipes_author_created', table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
